### ISSUE TITLE
Idle status stopped showing after upgrade from version 3 to 4

### ISSUE THREAD

**Issue by freetomik** [MayGo/tockler#346]
Idle status stopped showing after upgrade from v3.23.6 to v4.0.18. Instead of it there is now App `PERMISSION_ERROR` with window name `Active Window undefined` and Status is online.

Previous behaviour in v3.23.6:
![Image](https://github.com/user-attachments/assets/c4e47963-64ab-4d56-b7fb-1a64c6b2b870)

Current behaviour in v4.0.18:
![Image](https://github.com/user-attachments/assets/ebaf9648-343b-49ec-a647-70b92f554375)

Operating System:
Edition: Windows 10 Business
Version: 22H2
Build: 19045.5608
Performance: Windows Feature Experience Pack 1000.19061.1000.0

**Comment by MayGo** [comment]
hi, thanks for reporting.
should be fixed in 4.0.21

**Comment by freetomik** [comment]
Hi @MayGo, thanks for quick response. I tested it in v4.0.21, but sadly it behaves in the same way like in v4.0.18 - the error is still showing.

**Comment by MayGo** [comment]
I thought the problem was App items showing in Idle period.
The PERMISSION_ERROR is actually any error that occurs when getting active window does not result to anything. A bit misleading.

When is this error actually coming, if you analyze  it a bit. I can see it occurs sometimes, not always.

**Comment by MayGo** [comment]
Looking into this.
<img width="818" alt="Image" src="https://github.com/user-attachments/assets/ea9224ea-577b-4adb-a991-57e14688ec3d" />
Can you check if your Idle time is 60 under settings?

**Comment by freetomik** [comment]
Sure. I didn't have any value in that field - it was empty. When I put there 60, the Idle status is now showing correctly after 60 s.

**Comment by freetomik** [comment]
Well, not everything is correct yet - the App is showing for Idle status:
![Image](https://github.com/user-attachments/assets/c2195d94-4374-4382-bf74-392af09e4c6d)

Previously, there was no App in Idle status (which is I believe correct):
![Image](https://github.com/user-attachments/assets/e300cc3a-25cd-456a-9f2a-096149d0f1c7)

**Comment by freetomik** [comment]
Update, from yesterday it is OK.
![Image](https://github.com/user-attachments/assets/842495f2-d4c7-4fa0-bd9f-e9991e4c91f1)
